# Stage 1: Use a small Python base image
FROM python:3.10-slim

# Set environment variables to reduce image size
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    libpoppler-cpp-dev \
    poppler-utils \